%Tema realizata de Mihalea Andreas si Dima Darius
f  = @(x)(x^3-4*x^2+5*x-2);
x = sym('x');
df = matlabFunction(diff(sym(f), x));
phi = @(x) newton_raphson_functie(f(x), df(x), x);
[sol_aitken, iteratii_aitken, err_abs_aitken, err_rel_aitken, err_rez_aitken] = Aitken(f, phi,0,20,10^(-10));
[sol_nr, iteratii_nr, err_abs_nr, err_rel_nr, err_rez_nr] = NewtonRaphson(f, 0, 10^(-10));
obj = Steffensen(0, 10^(-10), 20, phi, 1);

sol_steff = obj.sol;
iteratii_steff = obj.iter * 3;
err_abs_steff = obj.Eroarea_Absoluta;
err_rel_steff = obj.Eroarea_Relativa;
err_rez_steff = obj.Eroarea_Reziduala;
count_vec_steff = 1:1:iteratii_steff;
Tsteff = table( ...
count_vec_steff', ...
sol_steff', ...
err_abs_steff', ... 
err_rel_steff', ...
err_rez_steff' ...
);

Tsteff.Properties.VariableNames = {'Index','Solutie_Steffensen','Eroarea_Absoluta','Eroarea_Relativa', 'Eroarea_Reziduala'};

count_vec_nr = (1:1:iteratii_nr);

Tnr = table( ...
count_vec_nr', ...
sol_nr', ...
err_abs_nr', ... 
err_rel_nr', ...
err_rez_nr' ...
);

Tnr.Properties.VariableNames = {'Index','Solutie_Newton','Eroarea_Absoluta','Eroarea_Relativa', 'Eroarea_Reziduala'};

count_vec_aitken = (1:1:iteratii_aitken);

Taitken = table( ...
count_vec_aitken', ...
sol_aitken', ...
err_abs_aitken', ... 
err_rel_aitken', ...
err_rez_aitken' ...
);

Taitken.Properties.VariableNames = {'Index','Solutie_Aitken','Eroarea_Absoluta','Eroarea_Relativa', 'Eroarea_Reziduala'};
